# 系統
sys:
    kaptcha-open: false #是否開啟登入時驗證碼 (true/false)
    kaptcha-length: 4 #驗證碼的長度
    # api接口模塊，是通過jwt認證的，如果要使用api模塊，则需要修改【加密秘鑰】
    jwt:
        header: token
        # 加密秘鑰
        secret: f4e2e52034348f86b67cde581c0f9eb5[vgk]
        # token有效時長，單位秒
        expire: 86400

# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-application-dev.ymlthreads: 1000
        min-spare-threads: 30
    port: 8888
    #打開注釋，則通過【http://localhost:8888/vgk/admin】訪問
    context-path: /vgk/admin

# mysql
spring:
    # 環境 dev|sit|uat|prod
    profiles:
        active: dev
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
    # jackson時間格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    http:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true
    # 指定靜態資源的路徑
    resources:
        static-locations: classpath:/static/,classpath:/views/
    redis:
        open: false  # 是否開啟redis緩存  true開啟   false關閉
        database: 0
        host: localhost
        port: 6379
        password:       # 密碼（默認为空）
        timeout: 6000  # 連接超時時長（毫秒）
        pool:
            max-active: 1000  # 連接池最大連接數（使用負值表示沒有限制）
            max-wait: -1      # 連接池最大阻塞等待時間（使用負值表示沒有限制）
            max-idle: 10      # 連接池中的最大空閒連接
            min-idle: 5       # 連接池中的最小空閒連接

# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml
    configLocation: classpath:mybatis.xml